### ISSUE TITLE
Update seems to have broken plug-in

### ISSUE THREAD

**Issue by commandcom** [CDuke/sublime-tfs#27]
Hi,
The last update seems to have broken something.  Restarted Sublime (Win7, v3.0 build 3143) and found none of the TFS commands worked.  From my console:

```
Package Control: Installing 1 upgrades
ignored packages updated to: ["Sublime TFS", "Vintage"]
unloading plugin Sublime TFS.sublime_tfs
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Upgraded Sublime TFS to 2017.12.06.07.28.58
reloading /C/Users/xxxx/AppData/Roaming/Sublime Text 3/Packages/Sublime TFS/sublime_tfs.py
ignored packages updated to: ["Vintage"]
reloading plugin Sublime TFS.sublime_tfs
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\Sublime TFS\sublime_tfs.py", line 142, in run_command
    working_dir = os.path.dirname(executable)
  File "./python3.3/ntpath.py", line 256, in dirname
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\Sublime TFS\sublime_tfs.py", line 182, in run
    (self.success, self.message) = self.method(self.m_path)
  File "C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\Sublime TFS\sublime_tfs.py", line 77, in checkout
    return self.run_command(commands, path, is_graph = self.always_is_graph)
  File "C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\Sublime TFS\sublime_tfs.py", line 153, in run_command
    trace_error("commands: [%s]\nis_graph: [%s]\nworking_dir: [%s]" % (commands, is_graph, working_dir))
UnboundLocalError: local variable 'commands' referenced before assignment
```
Seems to be having trouble getting the working directory?

**Comment by jefflaing** [comment]
Looks to me like it's having troubles getting the directory that contains either TF.EXE or TFPT.EXE.
You might want to check the settings of tf_path and tfpt_path to make sure they are populated correctly.

**Comment by commandcom** [comment]
Yep, that was exactly the problem.  I did not put my paths in the user settings file, so my configuration got reverted.  Thanks for the assist.
